# Site settings
title: a free multi-purpose color picker for Windows
email: jayprall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Color Cop is a free multi-purpose color picker for Microsoft Windows
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://colorcop.net" # the base hostname & protocol for your site
twitter_username: colorcop
github_username: colorcop

# Build settings
markdown: kramdown

# exclude some directories and files that shouldn't be published
exclude:
  - terraform
  - terragrunt
  - README.md
  - package*
  - playwright*
  - "*.toml"
  - tests
  - node_modules
  - vendor
